# Generated by Django 5.1.5 on 2025-03-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                ("complete", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_research_sessions",
                        to="organizations.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketResearchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("final_report", models.TextField(blank=True, null=True)),
                ("formate", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("output", models.JSONField(blank=True, null=True)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_tasks",
                        to="marketing_crew.marketresearch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SEOResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_name", models.CharField(max_length=255)),
                (
                    "competitors",
                    models.TextField(
                        help_text="List of competitors, separated by commas"
                    ),
                ),
                (
                    "target_audience",
                    models.TextField(help_text="Description of the target audience"),
                ),
                (
                    "ad_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ad budget in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "primary_goals",
                    models.TextField(help_text="Primary goals for the SEO campaign"),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_research_sessions",
                        to="organizations.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SEOResearchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("final_report", models.TextField(blank=True, null=True)),
                ("formate", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("output", models.JSONField(blank=True, null=True)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_tasks",
                        to="marketing_crew.seoresearch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competitors",
                    models.TextField(
                        help_text="List of competitors, separated by commas"
                    ),
                ),
                (
                    "campaign_theme",
                    models.CharField(help_text="Theme of the campaign", max_length=255),
                ),
                (
                    "target_audience",
                    models.CharField(
                        help_text="Target audience for the campaign", max_length=255
                    ),
                ),
                (
                    "platform",
                    models.TextField(
                        help_text="Platforms where the campaign will be run, separated by commas"
                    ),
                ),
                ("goal", models.TextField(help_text="Objective of the campaign")),
                ("complete", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_research_sessions",
                        to="organizations.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaResearchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("final_report", models.TextField(blank=True, null=True)),
                ("formate", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("output", models.JSONField(blank=True, null=True)),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_tasks",
                        to="marketing_crew.socialmediaresearch",
                    ),
                ),
            ],
        ),
    ]
