# Generated by Django 5.1.5 on 2025-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_userloginlog_eodreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="eodreport",
            name="agent_usage",
            field=models.JSONField(default=dict),
        ),
    ]
