# Generated by Django 5.1.5 on 2025-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_ticketissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
