# Generated by Django 5.1.5 on 2025-03-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_ticketissue_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinapikey",
            name="auth_head",
            field=models.TextField(blank=True, help_text="author head", null=True),
        ),
    ]
