# Generated by Django 5.1.5 on 2025-04-03 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_linkedinapikey_auth_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITSetup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "google_drive_link",
                    models.URLField(
                        help_text="Google Drive link for IT resources", max_length=500
                    ),
                ),
                ("instructions", models.TextField(help_text="IT setup instructions")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="it_setup",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicySetup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Upload policy document", upload_to="policies/"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Policy setup instructions"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_setup",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
