# Generated by Django 5.1.5 on 2025-03-19 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0004_chatmessage_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("employee_id", models.CharField(max_length=50)),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employee_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sessions",
                        to="organizations.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeOnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("final_report", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("output", models.JSONField(blank=True, null=True)),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hr_crew.onboarding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDocuments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relieving_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/relieving_letters/"
                    ),
                ),
                (
                    "salary_slip",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/salary_slips/"
                    ),
                ),
                (
                    "aadhaar_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/aadhaar/"
                    ),
                ),
                (
                    "pan_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/pan/"
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=11, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "onboarding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_documents",
                        to="hr_crew.onboarding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "education_qualification",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/education/"
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/resumes/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "onboarding_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr_crew.onboarding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("job_requirement", models.TextField()),
                ("expected_reach_out", models.IntegerField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_sessions",
                        to="organizations.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("resume_check", models.BooleanField(default=False)),
                ("ats_score", models.IntegerField(blank=True, null=True)),
                ("screening", models.BooleanField(default=False)),
                ("interview_status", models.BooleanField(default=False)),
                ("selected", models.BooleanField(default=False)),
                ("offer_letter", models.BooleanField(default=False)),
                (
                    "offer_letter_document",
                    models.FileField(blank=True, null=True, upload_to="offer_letters/"),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="hr_crew.recruitment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecruitmentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("final_report", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("output", models.JSONField(blank=True, null=True)),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hr_crew.recruitment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("time_slot", models.TimeField()),
                ("meet_link", models.CharField(blank=True, max_length=255, null=True)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="hr_crew.recruitment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="hr_crew.candidate",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="hr_crew.schedule",
                    ),
                ),
            ],
        ),
    ]
