# Generated by Django 5.1.5 on 2025-03-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apikey",
            old_name="encrypted_value",
            new_name="value",
        ),
    ]
