market_analyst_task:
  description: >
    Generate comprehensive reports analyzing current market trends. 
    Topic: {topic}
  expected_output: >
    A valid JSON object matching the MarketAnalystOutput schema. The 'response' field must summarize key market trends identified,
    their relevance to the {topic}, and their projected impact on the industry. The 'details' field must include: industry sector analyzed,
    list of trends with description, impact, and confidence level, plus the data sources used.
  agent: market_analyst

swot_analyst_task:
  description: >
    Perform a SWOT analysis on current and upcoming sales campaigns. 
    Topic: {topic}
  expected_output: >
    A valid JSON object matching the SWOTAnalysisOutput schema. The 'response' field must summarize the most important insight
    from the SWOT analysis for the {topic}, such as key opportunity or critical threat. The 'details' must include a full breakdown
    of strengths, weaknesses, opportunities, threats, and the strategic insight derived.
  agent: swot_analyst

competitor_analyst_task:
  description: >
    Build detailed reports on competitor activities, pricing strategies, 
    and key differentiators. 
    Topic: {topic}
  expected_output: >
    A valid JSON object conforming to the CompetitorAnalysisOutput schema. The 'response' must summarize competitive threats or
    opportunities uncovered relevant to the competitor_analyst_task, including key strategies observed. The 'details' must include competitor names,
    strategies, market positioning, recommendations, and risk factors.
  agent: competitor_analyst

pricing_strategist_task:
  description: >
    Create dynamic pricing models that adapt to market conditions 
    and competitor pricing trends. 
    Topic: {topic}
  expected_output: >
    A valid JSON object matching the PricingModelOutput schema. The 'response' must clearly describe the pricing strategy recommended
    for pricing_strategist_task and why it's suitable based on the analysis. The 'details' must include model description, pricing factors, data sources,
    and profitability forecast if available.
  agent: pricing_strategist

sales_pitch_specialist_task:
  description: >
    Draft personalized sales pitches emphasizing key differentiators and value propositions. 
    Topic: {topic}
  expected_output: >
    A valid JSON object conforming to the SalesPitchOutput schema. The 'response' must summarize the intent and approach of the pitch
    crafted for sales_pitch_specialist_task, including its appeal to the target demographic. The 'details' must include pitch content, persuasion points,
    audience profile, call to action, and estimated conversion rate if available.
  agent: sales_pitch_specialist
