market_analyst_task:
  description: >
    Generate comprehensive reports analyzing current market trends. 
    Topic: {topic}
  expected_output: >
    A valid JSON object matching the MarketAnalystOutput schema, which includes a textual summary of the market trends
    and a structured breakdown in the 'details' field covering: industry sector, a list of trends (with description,
    impact, and optional confidence level), and any data sources referenced.
  agent: market_analyst

swot_analyst_task:
  description: >
    Perform a SWOT analysis on current and upcoming sales campaigns. 
    Topic: {topic}
  expected_output: >
    A valid JSON object matching the SWOTAnalysisOutput schema, including an overall response summary and a 'details'
    field containing strengths, weaknesses, opportunities, threats (each with name, description, and optional implications),
    and strategic insights.
  agent: swot_analyst

competitor_analyst_task:
  description: >
    Build detailed reports on competitor activities, pricing strategies, 
    and key differentiators. 
    Topic: {topic}
  expected_output: >
    A valid JSON object following the CompetitorAnalysisOutput schema, containing a response summary and 'details' section
    with a list of competitors (including name, strategy, optional market positioning), actionable strategic recommendations,
    and any identified risk factors.
  agent: competitor_analyst

pricing_strategist_task:
  description: >
    Create dynamic pricing models that adapt to market conditions 
    and competitor pricing trends. 
    Topic: {topic}
  expected_output: >
    A valid JSON object conforming to the PricingModelOutput schema, including a response summary and a 'details' section
    describing the pricing model, key influencing factors (with descriptions and optional data sources), strategy, and an
    optional profitability forecast.
  agent: pricing_strategist

sales_pitch_specialist_task:
  description: >
    Draft personalized sales pitches emphasizing key differentiators and value propositions. 
    Topic: {topic}
  expected_output: >
    A valid JSON object adhering to the SalesPitchOutput schema, including a general response and a 'details' section
    that defines the target demographic, full pitch content, key persuasion points (with optional evidence), a call to action,
    and an optional estimated conversion rate.
  agent: sales_pitch_specialist
